/-
Copyright (c) 2025 ModularPhysics. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ModularPhysics Contributors
-/
import StringAlgebra.VOA.Examples.AffineLattice

namespace StringAlgebra.VOA

open scoped BigOperators

variable (R : Type*) [CommRing R]

/-! ## The Moonshine Module V♮

The Monster VOA, central to monstrous moonshine.
-/

/-- The Moonshine module V♮ (Frenkel-Lepowsky-Meurman construction) -/
structure MoonshineModule (R : Type*) [CommRing R] where
  /-- The Leech lattice Λ (rank 24, no roots) -/
  leechLattice : EvenLattice R
  leech_rank : leechLattice.rank = 24
  /-- No vectors of norm 2 -/
  no_roots : ∀ i, leechLattice.bilinearForm i i ≠ 2

namespace MoonshineModule

variable {R : Type*} [CommRing R]

/-- The central charge is c = 24 -/
def centralCharge (_V : MoonshineModule R) : R := 24

end MoonshineModule

/-! ## The Virasoro VOA

The Virasoro VOA L(c, 0) at central charge c.
-/

/-- The Virasoro VOA: the vacuum Verma module -/
structure VirasoroVOA (R : Type*) [CommRing R] where
  /-- The central charge -/
  c : R

namespace VirasoroVOA

variable {R : Type*} [CommRing R]

/-- The vacuum |0⟩ -/
noncomputable def vacuum (_V : VirasoroVOA R) : Unit := ()

/-- The conformal vector ω -/
noncomputable def conformalVector (_V : VirasoroVOA R) : Unit := ()

end VirasoroVOA

/-! ## W-algebras

W-algebras generalize the Virasoro algebra with higher spin currents.
-/

/-- A W-algebra with generators of spins s₁, s₂, ..., sₙ -/
structure WAlgebra (R : Type*) [CommRing R] where
  /-- The spins of the generating currents (s = 2 is the Virasoro) -/
  spins : List ℕ
  /-- The Virasoro is always present -/
  has_virasoro : 2 ∈ spins

namespace WAlgebra

variable {R : Type*} [CommRing R]

/-- W₃ algebra: generated by T (spin 2) and W (spin 3) -/
def W3 : WAlgebra R where
  spins := [2, 3]
  has_virasoro := by simp

/-- W_N algebra: generated by currents of spins 2, 3, ..., N -/
def WN (N : ℕ) (hN : N ≥ 2) : WAlgebra R where
  spins := List.range' 2 (N - 1)
  has_virasoro := by
    simp [List.mem_range']
    omega

end WAlgebra


end StringAlgebra.VOA
