/-
Copyright (c) 2025 ModularPhysics. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ModularPhysics Contributors
-/

import StringAlgebra.VOA.Basic
import StringAlgebra.VOA.FormalDistributions
import StringAlgebra.VOA.VertexAlgebra
import StringAlgebra.VOA.Virasoro
import StringAlgebra.VOA.Modules
import StringAlgebra.VOA.Examples

/-!
# Vertex Operator Algebras

This module provides a rigorous formalization of Vertex Operator Algebras (VOAs)
in Lean 4 using Mathlib.

## Overview

A vertex operator algebra is a fundamental algebraic structure in conformal field
theory and string theory. It consists of:

1. **State space** V: A ℤ-graded vector space V = ⊕_n V_n
2. **Vacuum** |0⟩ ∈ V_0: A distinguished vector
3. **Translation** T: V → V: An operator with T|0⟩ = 0
4. **Vertex operators** Y: V → End(V)[[z, z⁻¹]]: The state-field correspondence
5. **Conformal vector** ω ∈ V_2: Generates the Virasoro algebra

## Main Files

* `Basic.lean` - Formal Laurent series, graded spaces
* `FormalDistributions.lean` - Quantum fields, locality, OPE
* `VertexAlgebra.lean` - Main VOA definition and axioms
* `Virasoro.lean` - Virasoro algebra, minimal models
* `Modules.lean` - V-modules, intertwining operators, fusion rules
* `Examples.lean` - Heisenberg, affine, lattice VOAs

## Key Axioms

The VOA axioms are:

1. **Vacuum axiom**: Y(|0⟩, z) = Id
2. **Creation axiom**: Y(a, z)|0⟩|_{z=0} = a
3. **Translation axiom**: [T, Y(a, z)] = ∂_z Y(a, z)
4. **Locality**: (z-w)^N [Y(a,z), Y(b,w)] = 0 for some N

## References

* Borcherds, "Vertex algebras, Kac-Moody algebras, and the Monster" (1986)
* Frenkel, Lepowsky, Meurman, "Vertex Operator Algebras and the Monster" (1988)
* Kac, "Vertex Algebras for Beginners" (1998)
* Frenkel, Ben-Zvi, "Vertex Algebras and Algebraic Curves" (2004)

## Mathematical Content

### Formal Distributions

A formal distribution (quantum field) is a(z) = ∑_{n∈ℤ} a(n) z^{-n-1} where
a(n) ∈ End(V). The field property requires a(n)v = 0 for n >> 0.

### The Borcherds Identity

The fundamental identity relating products:
∑_{i≥0} (m choose i) (a(n+i)b)(m+k-i) =
∑_{i≥0} (-1)^i (n choose i) (a(m+n-i)b(k+i) - (-1)^n b(n+k-i)a(m+i))

### Conformal Structure

The Virasoro algebra is generated by L_n = ω_{n+1} with:
[L_m, L_n] = (m-n)L_{m+n} + (c/12)m(m²-1)δ_{m,-n}

### Modules and Fusion

A V-module M has a compatible action Y_M: V → End(M)[[z, z⁻¹]].
Fusion rules N_{ij}^k count intertwining operators.

-/

namespace StringAlgebra.VOA

-- Re-export main definitions
export FormalLaurentSeries (coeff residue derivative z zInv zPow)
export VertexAlgebra (Y vacuum translation nProduct)
export ConformalVertexAlgebra (conformalVector centralCharge L)
export VertexOperatorAlgebra (component)
export VAModule (Y_M action)

end StringAlgebra.VOA
